export default {
    FETCH_CONTRACT_STATIONS_REQUEST: 'FETCH_CONTRACT_STATIONS_REQUEST',
    FETCH_CONTRACT_STATIONS_FAILED: 'FETCH_CONTRACT_STATIONS_FAILED',
    FETCH_CONTRACT_STATIONS_SUCCEED: 'FETCH_CONTRACT_STATIONS_SUCCEED'
};

