export default {
    FETCH_FAVORITE_STATIONS_REQUEST: 'FETCH_FAVORITE_STATIONS_REQUEST',
    FETCH_FAVORITE_STATIONS_FAILED: 'FETCH_FAVORITE_STATIONS_FAILED',
    FETCH_FAVORITE_STATIONS_SUCCEED: 'FETCH_FAVORITE_STATIONS_SUCCEED',
    ADD_FAVORITE_STATION_REQUEST: 'ADD_FAVORITE_STATION_REQUEST',
    ADD_FAVORITE_STATION_FAILED: 'ADD_FAVORITE_STATION_FAILED',
    ADD_FAVORITE_STATION_SUCCEED: 'ADD_FAVORITE_STATION_SUCCEED',
    REMOVE_FAVORITE_STATION_REQUEST: 'REMOVE_FAVORITE_STATION_REQUEST',
    REMOVE_FAVORITE_STATION_FAILED: 'REMOVE_FAVORITE_STATION_FAILED',
    REMOVE_FAVORITE_STATION_SUCCEED: 'REMOVE_FAVORITE_STATION_SUCCEED'
};

