export default {
    FETCH_NEARBY_STATIONS_REQUEST: 'FETCH_NEARBY_STATIONS_REQUEST',
    FETCH_NEARBY_STATIONS_FAILED: 'FETCH_NEARBY_STATIONS_FAILED',
    FETCH_NEARBY_STATIONS_SUCCEED: 'FETCH_NEARBY_STATIONS_SUCCEED'
};

